server:
  port: 8083

spring:
  application:
    name: warehouse-service

doris:
  host: 127.0.0.1
  port: 9030
  database: bestwo_dw
  username: root
  password: DGut7850!!

logging:
  level:
    com.bestwo.dataplatform.warehouse: INFO
