apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: app
  labels:
    app.kubernetes.io/name: frontend-service
    app.kubernetes.io/part-of: bestwo-data-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frontend-service
  ports:
    - name: http
      port: 80
      targetPort: 80
