apiVersion: v1
kind: Service
metadata:
  name: warehouse-service
  namespace: app
  labels:
    app.kubernetes.io/name: warehouse-service
    app.kubernetes.io/part-of: bestwo-data-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: warehouse-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
