CREATE TABLE IF NOT EXISTS dwd_wx_order_detail (
    order_id VARCHAR(64) NOT NULL,
    order_no VARCHAR(64) NOT NULL,
    external_order_no VARCHAR(64) NULL,
    biz_type VARCHAR(32) NULL,
    order_source VARCHAR(32) NULL,
    order_title VARCHAR(128) NULL,
    order_description VARCHAR(255) NULL,
    buyer_id VARCHAR(64) NULL,
    buyer_nickname VARCHAR(128) NULL,
    currency VARCHAR(16) NULL,
    total_amount_fen BIGINT NULL,
    payable_amount_fen BIGINT NULL,
    paid_amount_fen BIGINT NULL,
    refunded_amount_fen BIGINT NULL,
    total_amount DECIMAL(18, 2) NULL,
    payable_amount DECIMAL(18, 2) NULL,
    paid_amount DECIMAL(18, 2) NULL,
    refund_amount DECIMAL(18, 2) NULL,
    order_status VARCHAR(32) NULL,
    pay_status VARCHAR(32) NULL,
    preferred_pay_platform VARCHAR(32) NULL,
    preferred_trade_type VARCHAR(32) NULL,
    success_pay_platform VARCHAR(32) NULL,
    order_time DATETIME NULL,
    pay_time DATETIME NULL,
    expired_time DATETIME NULL,
    closed_time DATETIME NULL,
    cancelled_time DATETIME NULL,
    latest_payment_order_no VARCHAR(64) NULL,
    latest_channel_order_no VARCHAR(128) NULL,
    payment_order_id VARCHAR(64) NULL,
    payment_order_no VARCHAR(64) NULL,
    payment_platform VARCHAR(32) NULL,
    payment_trade_type VARCHAR(32) NULL,
    payment_status VARCHAR(32) NULL,
    payment_request_amount_fen BIGINT NULL,
    payment_success_amount_fen BIGINT NULL,
    payment_request_amount DECIMAL(18, 2) NULL,
    payment_success_amount DECIMAL(18, 2) NULL,
    channel_order_no VARCHAR(128) NULL,
    channel_prepay_id VARCHAR(128) NULL,
    code_url STRING NULL,
    payment_fail_code VARCHAR(64) NULL,
    payment_fail_message VARCHAR(255) NULL,
    payment_expired_time DATETIME NULL,
    payment_success_time DATETIME NULL,
    payment_closed_time DATETIME NULL,
    latest_notify_time DATETIME NULL,
    latest_notify_status VARCHAR(64) NULL,
    latest_notify_process_status VARCHAR(32) NULL,
    stat_date DATE NULL,
    sync_time DATETIME NULL
)
UNIQUE KEY(order_id)
DISTRIBUTED BY HASH(order_id) BUCKETS 8
PROPERTIES (
    "replication_num" = "1"
);
