apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: infra
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/part-of: bestwo-data-platform
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: jenkins
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
