apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home
  namespace: infra
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/part-of: bestwo-data-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
